
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DepSearchWebServiceImplService", targetNamespace = "http://ws/", wsdlLocation = "http://rgai2:8080/depsearch/depsearch?wsdl")
public class DepSearchWebServiceImplService
    extends Service
{

    private final static URL DEPSEARCHWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DEPSEARCHWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName DEPSEARCHWEBSERVICEIMPLSERVICE_QNAME = new QName("http://ws/", "DepSearchWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://rgai2:8080/depsearch/depsearch?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEPSEARCHWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        DEPSEARCHWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public DepSearchWebServiceImplService() {
        super(__getWsdlLocation(), DEPSEARCHWEBSERVICEIMPLSERVICE_QNAME);
    }

    public DepSearchWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEPSEARCHWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public DepSearchWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, DEPSEARCHWEBSERVICEIMPLSERVICE_QNAME);
    }

    public DepSearchWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEPSEARCHWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public DepSearchWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DepSearchWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DepSearchWebServiceInterface
     */
    @WebEndpoint(name = "DepSearchWebServiceImplPort")
    public DepSearchWebServiceInterface getDepSearchWebServiceImplPort() {
        return super.getPort(new QName("http://ws/", "DepSearchWebServiceImplPort"), DepSearchWebServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DepSearchWebServiceInterface
     */
    @WebEndpoint(name = "DepSearchWebServiceImplPort")
    public DepSearchWebServiceInterface getDepSearchWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "DepSearchWebServiceImplPort"), DepSearchWebServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEPSEARCHWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw DEPSEARCHWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return DEPSEARCHWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
